import "@/styles.css";
import { Providers } from "./providers";
import { Metadata } from "next";

// Per-request CSP nonces require dynamic rendering so every framework script
// receives the nonce generated by middleware for that request.
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Lumen — AI Marketing Assistant",
  title: "AiAgent — AI Marketing Assistant",
  description:
    "A premium, minimal AI chat workspace for drafting, brainstorming and coding.",
  authors: [{ name: "Lumen" }],
    "A premium, minimal AI chat workspace for drafting, brainstorming and marketing strategy.",
  authors: [{ name: "AiAgent" }],
  openGraph: {
    title: "Lumen — AI Marketing Assistant",
    title: "AiAgent — AI Marketing Assistant",
    description: "Premium, minimal AI chat workspace.",
    type: "website",
  },
  twitter: {
    card: "summary",
    site: "@Lovable",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
